Tentativa de corrigir erro
Este erro apareceu , mas nao houve sucesso na sua resolução Library\PackageCache\com.unity.2d.common@4.2.1\Editor\InternalBridge\TexturePlatformSettings\TexturePlatformSettings.cs(149,23): error CS1061: 'TextureImportPlatformSettingsData' does not contain a definition for 'androidETC2FallbackOverrideProperty' and no accessible extension method 'androidETC2FallbackOverrideProperty' accepting a first argument of type 'TextureImportPlatformSettingsData' could be found (are you missing a using directive or an assembly reference?)